swagger: '2.0'
info:
  description: This is the API for Theors
  version: 1.0.0
  title: Theros API
  # put the contact info for your development or API team
  contact:
    email: tuantu.t@gmail.com

paths:
  /login:
    get:
      tags: [login]
      summary: get the list of users for login
      operationId: getUsers
      description: Return a list of users to choose from at login
      responses:
        200:
          description: The list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags: [login]
      summary: submit user input credentials
      operationId: postLogin
      description: Validates user login and password to return a token
      parameters: 
      - in: body
        name: loginRequest
        required: true
        schema:
          type: object
          properties:
            id:
              type: number
              description: the id of the user
            password:
              type: string
              description: the password of the user
          
      responses:
        200:
          description: a successful login request response
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: "#/definitions/User"
  /works:
    get:
      tags: [works]
      summary: get the list of works for a user
      operationId: getWorks
      description: Return the list of works that relate to a subject taught by the current user
      externalDocs:
        url: https://github.com/doc212/theros-api/wiki/getWorks
      responses:
        200:
          description: a list of works
          schema:
            type: array
            items:
              type: object
              properties:
                student:
                  type: string
                  description: The full name of the student
                class:
                  type: string
                  description: The description of the class of the student
                type:
                  type: string
                  enum: ["TDV, RAN"]
                  description: The type of work
                subject:
                  type: string
                  description: The subject of the work
                teacher:
                  type: string
                  description: The full name of the teacher
                result:
                  type: string
                  description: The result of the work
definitions:
  User:
    type: object
    properties:
      id:
        type: number
      fullname:
        type: string
      admin:
        type: boolean
      password:
        type: string
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /doc212/Theros/1.0.0
schemes:
 - https